# 타깃 링크 경계 검사. docs/01-ARCHITECTURE.md 2.2.
#
# 사용:
#   sbx_forbid_link(<target> <forbidden>...)   규칙 선언 (타깃이 아직 없어도 된다)
#   sbx_check_link_boundaries()                  모든 타깃 정의 후 한 번 호출
#
# 검사는 **전이적**이다. SandboxServer → X → SandboxRender 도 위반이다.
# 위반이 하나라도 있으면 FATAL_ERROR 로 구성을 중단한다.

function(sbx_forbid_link target)
    set_property(GLOBAL APPEND PROPERTY SBX_BOUNDARY_RULES "${target}")
    set_property(GLOBAL PROPERTY "SBX_BOUNDARY_FORBIDDEN_${target}" "${ARGN}")
endfunction()

# target 이 (직접 또는 간접으로) 링크하는 타깃 이름 목록을 out_var 에 돌려준다.
function(_sbx_collect_links target out_var)
    set(visited "")
    set(result "")
    set(stack "${target}")
    while(stack)
        list(POP_FRONT stack current)
        if(current IN_LIST visited)
            continue()
        endif()
        list(APPEND visited "${current}")
        if(NOT TARGET "${current}")
            continue()
        endif()

        get_target_property(type "${current}" TYPE)
        set(props INTERFACE_LINK_LIBRARIES)
        if(NOT type STREQUAL "INTERFACE_LIBRARY")
            list(APPEND props LINK_LIBRARIES)
        endif()

        foreach(prop IN LISTS props)
            get_target_property(libs "${current}" "${prop}")
            if(NOT libs)
                continue()
            endif()
            foreach(lib IN LISTS libs)
                # target_link_libraries(PRIVATE) 는 정적 라이브러리의 INTERFACE 쪽에 $<LINK_ONLY:x> 로 남는다.
                string(REGEX REPLACE "^\\$<LINK_ONLY:(.+)>$" "\\1" lib "${lib}")
                # 그 밖의 생성기 표현식과 "::@(dir)" 표식은 이름이 아니므로 건너뛴다.
                if(lib MATCHES "^\\$<" OR lib MATCHES "^::@")
                    continue()
                endif()
                if(NOT TARGET "${lib}")
                    continue()
                endif()
                get_target_property(aliased "${lib}" ALIASED_TARGET)
                if(aliased)
                    set(lib "${aliased}")
                endif()
                list(APPEND result "${lib}")
                list(APPEND stack "${lib}")
            endforeach()
        endforeach()
    endwhile()
    list(REMOVE_DUPLICATES result)
    set(${out_var} "${result}" PARENT_SCOPE)
endfunction()

function(sbx_check_link_boundaries)
    get_property(rules GLOBAL PROPERTY SBX_BOUNDARY_RULES)
    set(violations "")
    set(checked 0)
    foreach(target IN LISTS rules)
        if(NOT TARGET "${target}")
            continue()
        endif()
        math(EXPR checked "${checked} + 1")
        get_property(forbidden GLOBAL PROPERTY "SBX_BOUNDARY_FORBIDDEN_${target}")
        _sbx_collect_links("${target}" linked)
        foreach(bad IN LISTS forbidden)
            if(bad IN_LIST linked)
                list(APPEND violations "${target} must not link ${bad}")
            endif()
        endforeach()
    endforeach()

    if(violations)
        foreach(v IN LISTS violations)
            message(SEND_ERROR "SBX boundary violation: ${v}")
        endforeach()
        message(FATAL_ERROR "타깃 경계 규칙 위반 (docs/01-ARCHITECTURE.md 2장). 위 목록을 확인하십시오.")
    endif()
    message(STATUS "Sandbox: 링크 경계 검사 통과 (${checked}개 타깃)")
endfunction()
